on: [push, pull_request]

name: Main

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Components
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Format
        run: cargo fmt -- --check

  build_x86:
    name: Build x86
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86

      - run: which qemu-system-x86_64

      - name: Rustup
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install bootimage
        run: cargo install bootimage

      - name: Build
        run: cargo build

      - name: Create bootable image
        run: cargo bootimage

      - name: Test
        run: cargo test