on: [push, pull_request]

name: Continuous integration

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Components
        run: rustup component add rustfmt

      - name: Format
        run: cargo fmt -- --check

  build_x86:
    name: Build x86
    runs-on: ubuntu-latest
    env:
      RUST_TARGET: x86_64-unknown-none
    steps:
      - uses: actions/checkout@v3

      - name: Add Target
        run: rustup target add $RUST_TARGET

      - name: Install Components
        run: rustup component add llvm-tools-preview rust-src

      - name: Install bootimage
        run: cargo install bootimage

      - name: Build
        run: cargo build --target $RUST_TARGET

      - name: Create bootable image
        run: cargo bootimage